FILESEXTRAPATHS:prepend := "${THISDIR}/files:"

SRC_URI += "file://virtio.cfg"

KERNEL_EXTRA_ARGS += "CONFIG_VIRTIO_BLK=y CONFIG_XEN_BLKFRONT=y"

INITRAMFS_IMAGE_BUNDLE = "1"
INITRAMFS_FSTYPES = "cpio.gz"
